Create 1.0
SunForLife/algorithms-and-data-structures pull request #2
Opened 2017-12-24 18:17 UTC by SunForLife

First version for review

2017-12-24 18:37 UTC, danlark1 commented on 1.0
> +#include <deque>
убери ненужные инклюды

2017-12-24 18:37 UTC, danlark1 commented on 1.0
> +using namespace std;
без этого, пожалуйста

2017-12-24 18:37 UTC, danlark1 commented on 1.0
> +struct node{
пробел перед {

2017-12-24 18:37 UTC, danlark1 commented on 1.0
> +    shared_ptr <node> next;
скобку с типом надо бы к shared_ptr

2017-12-24 18:37 UTC, danlark1 commented on 1.0
> +class mlist {
почему mlist, не логичнее бы назвать mylist?

2017-12-24 18:37 UTC, danlark1 commented on 1.0
> +    shared_ptr <node> mbegin, mend;
same above

И сделай методы begin(), end(), как в STL, а то не очень как-то делать публичные поля

2017-12-24 18:37 UTC, danlark1 commented on 1.0
> +        mend->next = shared_ptr <node>(new node());
same above

2017-12-24 18:37 UTC, danlark1 commented on 1.0
> +    shared_ptr <node> it = l.mbegin;
same above

2017-12-25 20:50 UTC, danlark1 commented on 1.0
> +    std::shared_ptr <node>& begin() {
const метод

2017-12-25 20:50 UTC, danlark1 commented on 1.0
> +    std::shared_ptr <node>& end() {
const метод

2017-12-25 20:50 UTC, danlark1 commented on 1.0
> +    while (it != itm && it2 != mend) {
n log n созданий shared_ptr, общим решением всех ревьюеров мы решили заставлять такое переписывать на n аллокаций

2017-12-27 10:13 UTC, sartuhin requested changes
Комменты Данилы

2017-12-28 09:53 UTC, sartuhin requested changes

2017-12-28 09:53 UTC, sartuhin commented on 1.0
> +struct node {
Сделайте node шаблонным.

2017-12-28 09:53 UTC, sartuhin commented on 1.0
> +    int n = 0;
Размеры и счетчики должны быть беззнаковыми.

2017-12-28 09:53 UTC, sartuhin commented on 1.0
> +    int n;
Иницализация переменных.

2017-12-29 08:57 UTC, sartuhin approved these changes

2018-03-08 10:04 UTC, merged